import { Lead } from "./types";

/**
 * Mock data — substituir pela API real (GET /leads em
 * agents/lead-researcher) quando o Luís disponibilizar o acesso. Forma
 * alinhada 1:1 com os models do backend (ver lib/types.ts).
 */
export const mockLeads: Lead[] = [
  {
    id: "qm-001",
    market: "cascais",
    source: "idealista",
    status: "new",
    priority: "high",
    score: 94,
    property: {
      title: "Moradia V5 com piscina, Quinta da Marinha",
      zone: "Quinta da Marinha",
      micro_zone: "Resort",
      typology: "T5",
      property_type: "house",
      price_current: 2850000,
      price_initial: 3100000,
      price_reduction_amount: 250000,
      price_reduction_pct: 8.1,
      area_sqm: 420,
      price_per_sqm: 6786,
      days_on_market: 142,
      listing_url: "https://example.com/listing/qm-001",
      published_date: "2026-01-29",
      lat: 38.7143,
      lng: -9.4556,
      images: ["https://loremflickr.com/960/640/house,realestate?lock=12259", "https://loremflickr.com/960/640/house,realestate?lock=12260", "https://loremflickr.com/960/640/house,realestate?lock=12261", "https://loremflickr.com/960/640/house,realestate?lock=12262"],
    },
    seller: {
      type: "private",
      name: "Proprietário direto",
      agency_name: null,
      phone: null,
      email: null,
      contact_source: "idealista",
    },
    signals: [
      "price_reduction",
      "multiple_price_reductions",
      "days_120_179",
      "private_seller",
      "premium_zone",
      "stale_listing",
    ],
    ai_note: {
      diagnosis:
        "Moradia T5 de 420 m² na Quinta da Marinha, €2.85M (€6.786/m²), 142 dias no mercado com redução de preço de 8% já aplicada. Vendedor particular, sem agência.",
      owner_reading:
        "Os sinais sugerem alguma abertura a negociação — a redução de preço e os 142 dias sem agência envolvida podem indicar disponibilidade para uma conversa direta.",
      entry_angle:
        "Posicionamento de especialista local em Quinta da Marinha com compradores qualificados internacionais já a acompanhar este perfil de imóvel.",
      next_action: "Contactar esta semana — telefonar de manhã para confirmar disponibilidade e testar abertura a uma conversa.",
      suggested_message:
        "Bom dia, vi o seu imóvel em Quinta da Marinha. Trabalho muito focado nesta zona e tenho compradores qualificados à procura de imóveis com este perfil. Queria perceber se ainda está disponível e se faria sentido uma conversa rápida.",
    },
    manual_notes: null,
    price_history: [
      { price: 3100000, seen_at: "2026-01-29T09:00:00Z", source: "idealista" },
      { price: 2850000, seen_at: "2026-04-12T09:00:00Z", source: "idealista" },
    ],
    created_at: "2026-01-29T09:05:00Z",
    updated_at: "2026-06-15T08:00:00Z",
  },
  {
    id: "qm-002",
    market: "cascais",
    source: "imovirtual",
    status: "new",
    priority: "medium",
    score: 71,
    property: {
      title: "Apartamento T4 Quinta da Marinha",
      zone: "Quinta da Marinha",
      micro_zone: null,
      typology: "T4",
      property_type: "apartment",
      price_current: 1950000,
      price_initial: 1950000,
      price_reduction_amount: 0,
      price_reduction_pct: 0,
      area_sqm: 310,
      price_per_sqm: 6290,
      days_on_market: 18,
      listing_url: "https://example.com/listing/qm-002",
      published_date: "2026-06-01",
      lat: 38.7108,
      lng: -9.4511,
      images: ["https://loremflickr.com/960/640/house,realestate?lock=13220", "https://loremflickr.com/960/640/house,realestate?lock=13221", "https://loremflickr.com/960/640/house,realestate?lock=13222", "https://loremflickr.com/960/640/house,realestate?lock=13223"],
    },
    seller: {
      type: "agency",
      name: null,
      agency_name: "Premium Cascais Real Estate",
      phone: null,
      email: null,
      contact_source: "imovirtual",
    },
    signals: ["premium_zone"],
    ai_note: {
      diagnosis:
        "Apartamento T4 de 310 m² na Quinta da Marinha, €1.95M, anúncio recente (18 dias) sem redução de preço. Agência mediadora.",
      owner_reading:
        "Ainda é cedo no ciclo de venda — os sinais não indicam urgência por parte do vendedor.",
      entry_angle: "Acompanhamento do mercado de Quinta da Marinha e partilha de perspetiva sobre compradores ativos.",
      next_action: "Guardar para monitorização e reavaliar após a próxima atualização semanal.",
      suggested_message:
        "Bom dia, acompanho o mercado de Cascais de perto e vi este imóvel. Sem querer interferir com o trabalho atual, gostava de perceber se ainda está disponível e se faria sentido partilhar uma perspetiva sobre compradores ativos nesta zona.",
    },
    manual_notes: null,
    price_history: [{ price: 1950000, seen_at: "2026-06-01T09:00:00Z", source: "imovirtual" }],
    created_at: "2026-06-01T09:05:00Z",
    updated_at: "2026-06-01T09:05:00Z",
  },
  {
    id: "br-001",
    market: "cascais",
    source: "idealista",
    status: "contacted",
    priority: "high",
    score: 88,
    property: {
      title: "Moradia T3 com jardim, Birre",
      zone: "Birre",
      micro_zone: null,
      typology: "Moradia",
      property_type: "house",
      price_current: 1680000,
      price_initial: 1890000,
      price_reduction_amount: 210000,
      price_reduction_pct: 11.1,
      area_sqm: 280,
      price_per_sqm: 6000,
      days_on_market: 96,
      listing_url: "https://example.com/listing/br-001",
      published_date: "2026-03-15",
      lat: 38.7071,
      lng: -9.4442,
      images: ["https://loremflickr.com/960/640/house,realestate?lock=12119", "https://loremflickr.com/960/640/house,realestate?lock=12120", "https://loremflickr.com/960/640/house,realestate?lock=12121", "https://loremflickr.com/960/640/house,realestate?lock=12122"],
    },
    seller: {
      type: "private",
      name: "Proprietário direto",
      agency_name: null,
      phone: "+351 9XX XXX XXX",
      email: null,
      contact_source: "idealista",
    },
    signals: ["price_reduction", "days_90_119", "private_seller", "premium_zone", "seller_unresponsive"],
    ai_note: {
      diagnosis:
        "Moradia em Birre, €1.68M, redução de 11% e 96 dias no mercado. Vendedor particular com contacto direto disponível.",
      owner_reading: "A redução de preço sugere alguma flexibilidade para negociar.",
      entry_angle: "Especialista em Birre com compradores qualificados já em acompanhamento ativo.",
      next_action: "Já contactado — fazer follow-up se não houver resposta em 5 dias.",
      suggested_message:
        "Bom dia, vi o seu imóvel em Birre. Trabalho muito focado nesta zona e tenho compradores qualificados à procura de imóveis com este perfil. Ainda está disponível para uma conversa rápida?",
    },
    manual_notes: "Falei com o proprietário a 12/06, disse que ia pensar. Voltar a ligar dia 19.",
    price_history: [
      { price: 1890000, seen_at: "2026-03-15T09:00:00Z", source: "idealista" },
      { price: 1680000, seen_at: "2026-05-20T09:00:00Z", source: "idealista" },
    ],
    created_at: "2026-03-15T09:05:00Z",
    updated_at: "2026-06-12T17:30:00Z",
  },
  {
    id: "br-002",
    market: "cascais",
    source: "olx",
    status: "saved",
    priority: "medium",
    score: 68,
    property: {
      title: "T3 reformado em Birre",
      zone: "Birre",
      micro_zone: null,
      typology: "T3",
      property_type: "apartment",
      price_current: 980000,
      price_initial: 1050000,
      price_reduction_amount: 70000,
      price_reduction_pct: 6.7,
      area_sqm: 195,
      price_per_sqm: 5026,
      days_on_market: 64,
      listing_url: "https://example.com/listing/br-002",
      published_date: "2026-04-16",
      lat: 38.7036,
      lng: -9.4397,
      images: ["https://loremflickr.com/960/640/house,realestate?lock=13080", "https://loremflickr.com/960/640/house,realestate?lock=13081", "https://loremflickr.com/960/640/house,realestate?lock=13082", "https://loremflickr.com/960/640/house,realestate?lock=13083"],
    },
    seller: {
      type: "agency",
      name: null,
      agency_name: "Cascais Properties",
      phone: null,
      email: null,
      contact_source: "olx",
    },
    signals: ["price_reduction", "premium_zone"],
    ai_note: {
      diagnosis: "T3 reformado em Birre, €980k, uma redução de preço de 6.7%, 64 dias no mercado.",
      owner_reading: "Pode indicar abertura moderada a negociação, mas ainda dentro de prazos normais para a zona.",
      entry_angle: "Acompanhamento do mercado de Birre e perfil de compradores ativos na zona.",
      next_action: "Prioritizar esta semana se surgir uma segunda redução de preço.",
      suggested_message:
        "Bom dia, acompanho de perto o mercado de Cascais e vi este imóvel em Birre. Tenho clientes a comparar imóveis semelhantes — ainda está disponível?",
    },
    manual_notes: "Guardado para acompanhar evolução de preço.",
    price_history: [
      { price: 1050000, seen_at: "2026-04-16T09:00:00Z", source: "olx" },
      { price: 980000, seen_at: "2026-05-28T09:00:00Z", source: "olx" },
    ],
    created_at: "2026-04-16T09:05:00Z",
    updated_at: "2026-06-01T10:00:00Z",
  },
  {
    id: "gc-001",
    market: "cascais",
    source: "idealista",
    status: "new",
    priority: "high",
    score: 91,
    property: {
      title: "Moradia vista mar, Guincho",
      zone: "Guincho",
      micro_zone: "Praia do Guincho",
      typology: "Moradia",
      property_type: "house",
      price_current: 3400000,
      price_initial: 3400000,
      price_reduction_amount: 0,
      price_reduction_pct: 0,
      area_sqm: 510,
      price_per_sqm: 6667,
      days_on_market: 7,
      listing_url: "https://example.com/listing/gc-001",
      published_date: "2026-06-12",
      lat: 38.7340,
      lng: -9.4777,
      images: ["https://loremflickr.com/960/640/house,realestate?lock=75875", "https://loremflickr.com/960/640/house,realestate?lock=75876", "https://loremflickr.com/960/640/house,realestate?lock=75877", "https://loremflickr.com/960/640/house,realestate?lock=75878"],
    },
    seller: {
      type: "private",
      name: "Proprietário direto",
      agency_name: null,
      phone: null,
      email: null,
      contact_source: "idealista",
    },
    signals: ["private_seller", "premium_zone", "international_buyer_fit"],
    ai_note: {
      diagnosis: "Moradia com vista mar direta no Guincho, €3.4M, anúncio muito recente, vendedor particular.",
      owner_reading: "Ainda muito cedo no ciclo de venda — sem sinais de urgência, mas janela de oportunidade antes de entrar mediação.",
      entry_angle: "Acesso a compradores internacionais qualificados para ativos premium no Guincho.",
      next_action: "Contactar esta semana antes que o imóvel entre em mediação.",
      suggested_message:
        "Bom dia, vi o seu imóvel no Guincho e acredito que pode encaixar no perfil de compradores qualificados que procuram esta zona, incluindo clientes internacionais. Ainda está disponível?",
    },
    manual_notes: null,
    price_history: [{ price: 3400000, seen_at: "2026-06-12T09:00:00Z", source: "idealista" }],
    created_at: "2026-06-12T09:05:00Z",
    updated_at: "2026-06-12T09:05:00Z",
  },
  {
    id: "gc-002",
    market: "cascais",
    source: "imovirtual",
    status: "visit",
    priority: "low",
    score: 42,
    property: {
      title: "T4 com terraço, Guincho",
      zone: "Guincho",
      micro_zone: null,
      typology: "T4",
      property_type: "apartment",
      price_current: 2100000,
      price_initial: 2350000,
      price_reduction_amount: 250000,
      price_reduction_pct: 10.6,
      area_sqm: 340,
      price_per_sqm: 6176,
      days_on_market: 210,
      listing_url: "https://example.com/listing/gc-002",
      published_date: "2025-11-23",
      lat: 38.7305,
      lng: -9.4732,
      images: ["https://loremflickr.com/960/640/house,realestate?lock=76836", "https://loremflickr.com/960/640/house,realestate?lock=76837", "https://loremflickr.com/960/640/house,realestate?lock=76838", "https://loremflickr.com/960/640/house,realestate?lock=76839"],
    },
    seller: {
      type: "agency",
      name: null,
      agency_name: "Coastal Homes",
      phone: null,
      email: null,
      contact_source: "imovirtual",
    },
    signals: ["price_reduction", "multiple_price_reductions", "days_180_plus"],
    ai_note: {
      diagnosis: "T4 no Guincho, €2.1M, 210 dias no mercado, duas reduções de preço acumuladas (-10.6%).",
      owner_reading: "Tempo elevado no mercado sugere alguma motivação, mas agência indica negociação avançada com outro comprador.",
      entry_angle: "Manter contacto discreto caso a negociação atual não avance.",
      next_action: "Visita feita a 28/05 — aguardar desenvolvimento da outra negociação antes de novo contacto.",
      suggested_message:
        "Bom dia, acompanho o mercado de Cascais de perto. Sem querer interferir com o processo atual, gostava de manter o contacto caso surja oportunidade.",
    },
    manual_notes: "Agência confirmou negociação avançada com outro comprador. Visitar de novo só se cair.",
    price_history: [
      { price: 2350000, seen_at: "2025-11-23T09:00:00Z", source: "imovirtual" },
      { price: 2200000, seen_at: "2026-02-10T09:00:00Z", source: "imovirtual" },
      { price: 2100000, seen_at: "2026-04-05T09:00:00Z", source: "imovirtual" },
    ],
    created_at: "2025-11-23T09:05:00Z",
    updated_at: "2026-05-28T16:00:00Z",
  },
  {
    id: "me-001",
    market: "cascais",
    source: "idealista",
    status: "new",
    priority: "high",
    score: 86,
    property: {
      title: "T3 renovado, Monte Estoril",
      zone: "Monte Estoril",
      micro_zone: null,
      typology: "T3",
      property_type: "apartment",
      price_current: 1150000,
      price_initial: 1290000,
      price_reduction_amount: 140000,
      price_reduction_pct: 10.9,
      area_sqm: 175,
      price_per_sqm: 6571,
      days_on_market: 118,
      listing_url: "https://example.com/listing/me-001",
      published_date: "2026-02-21",
      lat: 38.7057,
      lng: -9.4126,
      images: ["https://loremflickr.com/960/640/house,realestate?lock=43359", "https://loremflickr.com/960/640/house,realestate?lock=43360", "https://loremflickr.com/960/640/house,realestate?lock=43361", "https://loremflickr.com/960/640/house,realestate?lock=43362"],
    },
    seller: {
      type: "private",
      name: "Proprietário direto",
      agency_name: null,
      phone: null,
      email: null,
      contact_source: "idealista",
    },
    signals: ["price_reduction", "days_90_119", "private_seller", "premium_zone"],
    ai_note: {
      diagnosis: "T3 renovado em Monte Estoril, €1.15M, redução de 11% e 118 dias no mercado, vendedor particular.",
      owner_reading: "Os sinais sugerem motivação real para vender — redução significativa combinada com tempo no mercado.",
      entry_angle: "Especialista local em Monte Estoril com compradores qualificados ativos.",
      next_action: "Prioritizar esta semana — telefonar de manhã para confirmar disponibilidade.",
      suggested_message:
        "Bom dia, vi o seu imóvel em Monte Estoril. É uma zona que acompanho de perto e onde tenho clientes qualificados a comparar imóveis semelhantes. Faria sentido falarmos rapidamente?",
    },
    manual_notes: null,
    price_history: [
      { price: 1290000, seen_at: "2026-02-21T09:00:00Z", source: "idealista" },
      { price: 1150000, seen_at: "2026-05-10T09:00:00Z", source: "idealista" },
    ],
    created_at: "2026-02-21T09:05:00Z",
    updated_at: "2026-06-10T09:00:00Z",
  },
  {
    id: "me-002",
    market: "cascais",
    source: "casa_sapo",
    status: "new",
    priority: "low",
    score: 38,
    property: {
      title: "T2 funcional, Monte Estoril",
      zone: "Monte Estoril",
      micro_zone: null,
      typology: "T2",
      property_type: "apartment",
      price_current: 720000,
      price_initial: 720000,
      price_reduction_amount: 0,
      price_reduction_pct: 0,
      area_sqm: 110,
      price_per_sqm: 6545,
      days_on_market: 22,
      listing_url: "https://example.com/listing/me-002",
      published_date: "2026-05-28",
      lat: 38.7022,
      lng: -9.4081,
      images: ["https://loremflickr.com/960/640/house,realestate?lock=44320", "https://loremflickr.com/960/640/house,realestate?lock=44321", "https://loremflickr.com/960/640/house,realestate?lock=44322", "https://loremflickr.com/960/640/house,realestate?lock=44323"],
    },
    seller: {
      type: "agency",
      name: null,
      agency_name: "Estoril Realty",
      phone: null,
      email: null,
      contact_source: "casa_sapo",
    },
    signals: ["premium_zone"],
    ai_note: {
      diagnosis: "T2 de entrada em Monte Estoril, €720k, sem sinais de urgência de venda.",
      owner_reading: "Sem indicação de motivação acima da média de mercado.",
      entry_angle: "Monitorizar evolução, sem abordagem prioritária.",
      next_action: "Guardar para monitorização e reavaliar após a próxima atualização semanal.",
      suggested_message:
        "Bom dia, acompanho o mercado de Cascais de perto e vi este imóvel. Gostava de perceber se ainda está disponível.",
    },
    manual_notes: null,
    price_history: [{ price: 720000, seen_at: "2026-05-28T09:00:00Z", source: "casa_sapo" }],
    created_at: "2026-05-28T09:05:00Z",
    updated_at: "2026-05-28T09:05:00Z",
  },
  {
    id: "cc-001",
    market: "cascais",
    source: "idealista",
    status: "contacted",
    priority: "medium",
    score: 65,
    property: {
      title: "T3 central, Cascais Centro",
      zone: "Cascais Centro",
      micro_zone: null,
      typology: "T3",
      property_type: "apartment",
      price_current: 890000,
      price_initial: 980000,
      price_reduction_amount: 90000,
      price_reduction_pct: 9.2,
      area_sqm: 150,
      price_per_sqm: 5933,
      days_on_market: 75,
      listing_url: "https://example.com/listing/cc-001",
      published_date: "2026-04-05",
      lat: 38.6983,
      lng: -9.4235,
      images: ["https://loremflickr.com/960/640/house,realestate?lock=69127", "https://loremflickr.com/960/640/house,realestate?lock=69128", "https://loremflickr.com/960/640/house,realestate?lock=69129", "https://loremflickr.com/960/640/house,realestate?lock=69130"],
    },
    seller: {
      type: "private",
      name: "Proprietário direto",
      agency_name: null,
      phone: null,
      email: null,
      contact_source: "idealista",
    },
    signals: ["price_reduction", "days_90_119", "private_seller"],
    ai_note: {
      diagnosis: "T3 central em Cascais, €890k, redução de 9%, 75 dias no mercado, localização de alta liquidez.",
      owner_reading: "Redução de preço sugere alguma abertura a negociação.",
      entry_angle: "Acompanhamento do mercado central de Cascais e perfil de compradores ativos.",
      next_action: "Aguardar resposta — fazer follow-up se não houver retorno em 5 dias.",
      suggested_message:
        "Bom dia, vi o seu imóvel em Cascais. Trabalho muito focado nesta zona e tenho compradores qualificados à procura de imóveis com este perfil. Ainda está disponível?",
    },
    manual_notes: "Primeira mensagem enviada a 14/06. Sem resposta ainda.",
    price_history: [
      { price: 980000, seen_at: "2026-04-05T09:00:00Z", source: "idealista" },
      { price: 890000, seen_at: "2026-05-30T09:00:00Z", source: "idealista" },
    ],
    created_at: "2026-04-05T09:05:00Z",
    updated_at: "2026-06-14T11:00:00Z",
  },
  {
    id: "cc-002",
    market: "cascais",
    source: "imovirtual",
    status: "new",
    priority: "medium",
    score: 58,
    property: {
      title: "T2 reformado, Cascais Centro",
      zone: "Cascais Centro",
      micro_zone: null,
      typology: "T2",
      property_type: "apartment",
      price_current: 650000,
      price_initial: 690000,
      price_reduction_amount: 40000,
      price_reduction_pct: 5.8,
      area_sqm: 95,
      price_per_sqm: 6842,
      days_on_market: 45,
      listing_url: "https://example.com/listing/cc-002",
      published_date: "2026-05-05",
      lat: 38.6948,
      lng: -9.4190,
      images: ["https://loremflickr.com/960/640/house,realestate?lock=70088", "https://loremflickr.com/960/640/house,realestate?lock=70089", "https://loremflickr.com/960/640/house,realestate?lock=70090", "https://loremflickr.com/960/640/house,realestate?lock=70091"],
    },
    seller: {
      type: "agency",
      name: null,
      agency_name: "Cascais Properties",
      phone: null,
      email: null,
      contact_source: "imovirtual",
    },
    signals: ["price_reduction"],
    ai_note: {
      diagnosis: "T2 reformado em Cascais Centro, €650k, pequena redução de preço, zona com alta liquidez.",
      owner_reading: "Sinal moderado, dentro de prazos normais para a zona.",
      entry_angle: "Acompanhamento do mercado central de Cascais.",
      next_action: "Adicionar à fila de outreach.",
      suggested_message:
        "Bom dia, acompanho o mercado de Cascais de perto e vi este imóvel. Gostava de perceber se ainda está disponível e se faria sentido uma conversa rápida.",
    },
    manual_notes: null,
    price_history: [
      { price: 690000, seen_at: "2026-05-05T09:00:00Z", source: "imovirtual" },
      { price: 650000, seen_at: "2026-06-08T09:00:00Z", source: "imovirtual" },
    ],
    created_at: "2026-05-05T09:05:00Z",
    updated_at: "2026-06-08T09:05:00Z",
  },
  {
    id: "es-001",
    market: "cascais",
    source: "idealista",
    status: "new",
    priority: "medium",
    score: 73,
    property: {
      title: "T4 perto do casino, Estoril",
      zone: "Estoril",
      micro_zone: null,
      typology: "T4",
      property_type: "apartment",
      price_current: 1480000,
      price_initial: 1480000,
      price_reduction_amount: 0,
      price_reduction_pct: 0,
      area_sqm: 260,
      price_per_sqm: 5692,
      days_on_market: 12,
      listing_url: "https://example.com/listing/es-001",
      published_date: "2026-06-07",
      lat: 38.7059,
      lng: -9.3998,
      images: ["https://loremflickr.com/960/640/house,realestate?lock=12213", "https://loremflickr.com/960/640/house,realestate?lock=12214", "https://loremflickr.com/960/640/house,realestate?lock=12215", "https://loremflickr.com/960/640/house,realestate?lock=12216"],
    },
    seller: {
      type: "private",
      name: "Proprietário direto",
      agency_name: null,
      phone: null,
      email: null,
      contact_source: "idealista",
    },
    signals: ["private_seller"],
    ai_note: {
      diagnosis: "T4 no Estoril, €1.48M, perto do casino, anúncio recente, vendedor particular.",
      owner_reading: "Ainda cedo no ciclo de venda, mas vendedor particular vale contacto inicial.",
      entry_angle: "Especialista local no Estoril com compradores qualificados.",
      next_action: "Contactar esta semana para apresentação inicial.",
      suggested_message:
        "Bom dia, vi o seu imóvel no Estoril. Trabalho muito focado nesta zona e tenho compradores qualificados à procura de imóveis com este perfil. Ainda está disponível?",
    },
    manual_notes: null,
    price_history: [{ price: 1480000, seen_at: "2026-06-07T09:00:00Z", source: "idealista" }],
    created_at: "2026-06-07T09:05:00Z",
    updated_at: "2026-06-07T09:05:00Z",
  },
  {
    id: "es-002",
    market: "cascais",
    source: "idealista",
    status: "new",
    priority: "high",
    score: 90,
    property: {
      title: "Moradia clássica, Estoril",
      zone: "Estoril",
      micro_zone: null,
      typology: "Moradia",
      property_type: "house",
      price_current: 2250000,
      price_initial: 2600000,
      price_reduction_amount: 350000,
      price_reduction_pct: 13.5,
      area_sqm: 390,
      price_per_sqm: 5769,
      days_on_market: 264,
      listing_url: "https://example.com/listing/es-002",
      published_date: "2025-09-29",
      lat: 38.7024,
      lng: -9.3953,
      images: ["https://loremflickr.com/960/640/house,realestate?lock=13174", "https://loremflickr.com/960/640/house,realestate?lock=13175", "https://loremflickr.com/960/640/house,realestate?lock=13176", "https://loremflickr.com/960/640/house,realestate?lock=13177"],
    },
    seller: {
      type: "private",
      name: "Proprietário direto",
      agency_name: null,
      phone: null,
      email: null,
      contact_source: "idealista",
    },
    signals: ["price_reduction", "multiple_price_reductions", "days_180_plus", "private_seller"],
    ai_note: {
      diagnosis: "Moradia clássica no Estoril, €2.25M, mais de 8 meses no mercado, redução acumulada de 13.5%, vendedor particular.",
      owner_reading: "Sinal forte de motivação para vender — tempo elevado no mercado combinado com redução significativa de preço.",
      entry_angle: "Especialista no Estoril com acesso a compradores internacionais qualificados.",
      next_action: "Prioritizar esta semana — combinação de redução de preço e mais de 180 dias no mercado.",
      suggested_message:
        "Bom dia, vi o seu imóvel no Estoril. Acompanho de perto este mercado e tenho clientes a procurar ativos com este perfil. Ainda está disponível para visita?",
    },
    manual_notes: null,
    price_history: [
      { price: 2600000, seen_at: "2025-09-29T09:00:00Z", source: "idealista" },
      { price: 2400000, seen_at: "2026-01-15T09:00:00Z", source: "idealista" },
      { price: 2250000, seen_at: "2026-04-02T09:00:00Z", source: "idealista" },
    ],
    created_at: "2025-09-29T09:05:00Z",
    updated_at: "2026-06-16T09:00:00Z",
  },
  {
    id: "es-003",
    market: "cascais",
    source: "imovirtual",
    status: "new",
    priority: "low",
    score: 35,
    property: {
      title: "T3 standard, Estoril",
      zone: "Estoril",
      micro_zone: null,
      typology: "T3",
      property_type: "apartment",
      price_current: 940000,
      price_initial: 940000,
      price_reduction_amount: 0,
      price_reduction_pct: 0,
      area_sqm: 160,
      price_per_sqm: 5875,
      days_on_market: 5,
      listing_url: "https://example.com/listing/es-003",
      published_date: "2026-06-14",
      lat: 38.7052,
      lng: -9.3948,
      images: ["https://loremflickr.com/960/640/house,realestate?lock=14135", "https://loremflickr.com/960/640/house,realestate?lock=14136", "https://loremflickr.com/960/640/house,realestate?lock=14137", "https://loremflickr.com/960/640/house,realestate?lock=14138"],
    },
    seller: {
      type: "agency",
      name: null,
      agency_name: "Estoril Realty",
      phone: null,
      email: null,
      contact_source: "imovirtual",
    },
    signals: [],
    ai_note: {
      diagnosis: "T3 standard no Estoril, €940k, anúncio muito recente, sem sinais relevantes ainda.",
      owner_reading: "Demasiado cedo para inferir motivação.",
      entry_angle: "Monitorizar evolução do anúncio.",
      next_action: "Guardar para monitorização e reavaliar após a próxima atualização semanal.",
      suggested_message:
        "Bom dia, acompanho o mercado de Cascais de perto e vi este imóvel. Gostava de perceber se ainda está disponível.",
    },
    manual_notes: null,
    price_history: [{ price: 940000, seen_at: "2026-06-14T09:00:00Z", source: "imovirtual" }],
    created_at: "2026-06-14T09:05:00Z",
    updated_at: "2026-06-14T09:05:00Z",
  },
  {
    id: "qm-003",
    market: "cascais",
    source: "imovirtual",
    status: "not_relevant",
    priority: "medium",
    score: 70,
    property: {
      title: "Moradia de luxo, Quinta da Marinha",
      zone: "Quinta da Marinha",
      micro_zone: "Resort",
      typology: "Moradia",
      property_type: "house",
      price_current: 4200000,
      price_initial: 4200000,
      price_reduction_amount: 0,
      price_reduction_pct: 0,
      area_sqm: 580,
      price_per_sqm: 7241,
      days_on_market: 30,
      listing_url: "https://example.com/listing/qm-003",
      published_date: "2026-05-20",
      lat: 38.7136,
      lng: -9.4506,
      images: ["https://loremflickr.com/960/640/house,realestate?lock=14181", "https://loremflickr.com/960/640/house,realestate?lock=14182", "https://loremflickr.com/960/640/house,realestate?lock=14183", "https://loremflickr.com/960/640/house,realestate?lock=14184"],
    },
    seller: {
      type: "agency",
      name: null,
      agency_name: "Sotheby's Realty",
      phone: null,
      email: null,
      contact_source: "imovirtual",
    },
    signals: ["premium_zone"],
    ai_note: {
      diagnosis: "Moradia de luxo em Quinta da Marinha, €4.2M, agência de grande promotor internacional.",
      owner_reading: "Canal de mediação de grande promotor com baixa probabilidade de oportunidade direta.",
      entry_angle: "Não aplicável — canal de baixa conversão para abordagem direta.",
      next_action: "Sem ação necessária.",
      suggested_message: null,
    },
    manual_notes: "Marcado como não relevante — canal de agência de grande promotor (Sotheby's).",
    price_history: [{ price: 4200000, seen_at: "2026-05-20T09:00:00Z", source: "imovirtual" }],
    created_at: "2026-05-20T09:05:00Z",
    updated_at: "2026-05-22T10:00:00Z",
  },
  {
    id: "br-003",
    market: "cascais",
    source: "idealista",
    status: "visit",
    priority: "high",
    score: 82,
    property: {
      title: "T4 com anexo, Birre",
      zone: "Birre",
      micro_zone: null,
      typology: "T4",
      property_type: "house",
      price_current: 1320000,
      price_initial: 1480000,
      price_reduction_amount: 160000,
      price_reduction_pct: 10.8,
      area_sqm: 250,
      price_per_sqm: 5280,
      days_on_market: 88,
      listing_url: "https://example.com/listing/br-003",
      published_date: "2026-03-23",
      lat: 38.7064,
      lng: -9.4392,
      images: ["https://loremflickr.com/960/640/house,realestate?lock=14041", "https://loremflickr.com/960/640/house,realestate?lock=14042", "https://loremflickr.com/960/640/house,realestate?lock=14043", "https://loremflickr.com/960/640/house,realestate?lock=14044"],
    },
    seller: {
      type: "private",
      name: "Proprietário direto",
      agency_name: null,
      phone: "+351 9XX XXX XXX",
      email: null,
      contact_source: "idealista",
    },
    signals: ["price_reduction", "days_90_119", "private_seller", "premium_zone"],
    ai_note: {
      diagnosis: "T4 com anexo em Birre, €1.32M, redução de 10.8%, vendedor particular recetivo a contacto.",
      owner_reading: "Sinais fortes de motivação — vendedor já demonstrou abertura a contrapropostas em conversa anterior.",
      entry_angle: "Aprofundar relação já estabelecida e avançar para visita.",
      next_action: "Visita marcada — preparar contraproposta com base em comparáveis da zona.",
      suggested_message:
        "Bom dia, conforme falámos, gostava de combinar a visita ao imóvel em Birre para esta semana. Que dia lhe é mais conveniente?",
    },
    manual_notes: "Visita agendada para 22/06 às 10h. Proprietário recetivo a contrapropostas.",
    price_history: [
      { price: 1480000, seen_at: "2026-03-23T09:00:00Z", source: "idealista" },
      { price: 1320000, seen_at: "2026-05-18T09:00:00Z", source: "idealista" },
    ],
    created_at: "2026-03-23T09:05:00Z",
    updated_at: "2026-06-17T14:00:00Z",
  },
  {
    id: "gc-003",
    market: "cascais",
    source: "casa_sapo",
    status: "new",
    priority: "medium",
    score: 62,
    property: {
      title: "T3 vista parcial mar, Guincho",
      zone: "Guincho",
      micro_zone: null,
      typology: "T3",
      property_type: "apartment",
      price_current: 1550000,
      price_initial: 1550000,
      price_reduction_amount: 0,
      price_reduction_pct: 0,
      area_sqm: 190,
      price_per_sqm: 8158,
      days_on_market: 50,
      listing_url: "https://example.com/listing/gc-003",
      published_date: "2026-04-30",
      lat: 38.7333,
      lng: -9.4727,
      images: ["https://loremflickr.com/960/640/house,realestate?lock=77797", "https://loremflickr.com/960/640/house,realestate?lock=77798", "https://loremflickr.com/960/640/house,realestate?lock=77799", "https://loremflickr.com/960/640/house,realestate?lock=77800"],
    },
    seller: {
      type: "private",
      name: "Proprietário direto",
      agency_name: null,
      phone: null,
      email: null,
      contact_source: "casa_sapo",
    },
    signals: ["private_seller", "premium_zone", "price_m2_above_zone"],
    ai_note: {
      diagnosis: "T3 com vista parcial de mar no Guincho, €1.55M (€8.158/m², acima da média da zona), sem redução de preço ainda.",
      owner_reading: "Preço acima da referência da zona sem justificação clara visível — pode haver espaço para negociação numa conversa.",
      entry_angle: "Especialista no Guincho com perspetiva sobre posicionamento de preço face a comparáveis.",
      next_action: "Contactar esta semana para apresentação inicial.",
      suggested_message:
        "Bom dia, vi o seu imóvel no Guincho. Acompanho de perto este mercado e tenho clientes a procurar ativos com este perfil. Faria sentido uma conversa rápida?",
    },
    manual_notes: null,
    price_history: [{ price: 1550000, seen_at: "2026-04-30T09:00:00Z", source: "casa_sapo" }],
    created_at: "2026-04-30T09:05:00Z",
    updated_at: "2026-04-30T09:05:00Z",
  },
  {
    id: "me-003",
    market: "cascais",
    source: "idealista",
    status: "new",
    priority: "high",
    score: 84,
    property: {
      title: "Penthouse T5, Monte Estoril",
      zone: "Monte Estoril",
      micro_zone: null,
      typology: "T5",
      property_type: "apartment",
      price_current: 2680000,
      price_initial: 2980000,
      price_reduction_amount: 300000,
      price_reduction_pct: 10.1,
      area_sqm: 400,
      price_per_sqm: 6700,
      days_on_market: 175,
      listing_url: "https://example.com/listing/me-003",
      published_date: "2025-12-23",
      lat: 38.7050,
      lng: -9.4076,
      images: ["https://loremflickr.com/960/640/house,realestate?lock=45281", "https://loremflickr.com/960/640/house,realestate?lock=45282", "https://loremflickr.com/960/640/house,realestate?lock=45283", "https://loremflickr.com/960/640/house,realestate?lock=45284"],
    },
    seller: {
      type: "agency",
      name: null,
      agency_name: "Monte Estoril Homes",
      phone: null,
      email: null,
      contact_source: "idealista",
    },
    signals: ["price_reduction", "days_120_179", "premium_zone"],
    ai_note: {
      diagnosis: "Penthouse T5 em Monte Estoril, €2.68M, redução de 10% e quase 6 meses no mercado.",
      owner_reading: "Tempo elevado no mercado e redução de preço sugerem alguma flexibilidade, possivelmente também na comissão da agência.",
      entry_angle: "Acompanhamento do mercado de Monte Estoril e partilha de perspetiva sobre compradores ativos.",
      next_action: "Prioritizar esta semana — combinação de redução de preço com 120+ dias no mercado.",
      suggested_message:
        "Bom dia, acompanho o mercado de Cascais de perto e vi este imóvel em Monte Estoril. Sem querer interferir com o trabalho atual, gostava de perceber se ainda está disponível.",
    },
    manual_notes: null,
    price_history: [
      { price: 2980000, seen_at: "2025-12-23T09:00:00Z", source: "idealista" },
      { price: 2680000, seen_at: "2026-04-08T09:00:00Z", source: "idealista" },
    ],
    created_at: "2025-12-23T09:05:00Z",
    updated_at: "2026-06-13T09:00:00Z",
  },
  {
    id: "cc-003",
    market: "cascais",
    source: "olx",
    status: "new",
    priority: "low",
    score: 30,
    property: {
      title: "T2 de entrada, Cascais Centro",
      zone: "Cascais Centro",
      micro_zone: null,
      typology: "T2",
      property_type: "apartment",
      price_current: 580000,
      price_initial: 580000,
      price_reduction_amount: 0,
      price_reduction_pct: 0,
      area_sqm: 80,
      price_per_sqm: 7250,
      days_on_market: 9,
      listing_url: "https://example.com/listing/cc-003",
      published_date: "2026-06-10",
      lat: 38.6976,
      lng: -9.4185,
      images: ["https://loremflickr.com/960/640/house,realestate?lock=71049", "https://loremflickr.com/960/640/house,realestate?lock=71050", "https://loremflickr.com/960/640/house,realestate?lock=71051", "https://loremflickr.com/960/640/house,realestate?lock=71052"],
    },
    seller: {
      type: "private",
      name: "Proprietário direto",
      agency_name: null,
      phone: null,
      email: null,
      contact_source: "olx",
    },
    signals: ["private_seller"],
    ai_note: {
      diagnosis: "T2 de entrada em Cascais Centro, €580k, anúncio recente, baixa urgência aparente.",
      owner_reading: "Sem indicação de motivação acima da média de mercado.",
      entry_angle: "Monitorizar evolução, sem abordagem prioritária.",
      next_action: "Guardar para monitorização e reavaliar após a próxima atualização semanal.",
      suggested_message:
        "Bom dia, vi o seu imóvel em Cascais. Gostava de perceber se ainda está disponível.",
    },
    manual_notes: null,
    price_history: [{ price: 580000, seen_at: "2026-06-10T09:00:00Z", source: "olx" }],
    created_at: "2026-06-10T09:05:00Z",
    updated_at: "2026-06-10T09:05:00Z",
  },
];
