import { Lead } from "./types";

/**
 * Mock data — substituir por leitura do Supabase quando o Luís disponibilizar
 * o acesso. Forma alinhada com os models do backend (ver CLAUDE.md).
 */
export const mockLeads: Lead[] = [
  {
    id: "qm-001",
    zone: "Quinta da Marinha",
    zone_tier: 1,
    typology: "T5",
    price_current: 2850000,
    price_initial: 3100000,
    area_sqm: 420,
    days_on_market: 142,
    seller_type: "particular",
    priority: "HIGH",
    score: 94,
    status: "Por contactar",
    listing_url: "https://example.com/listing/qm-001",
    commercial_note:
      "Redução de preço de 8% nos últimos 3 meses. Proprietário particular, sem agência envolvida — maior margem de negociação direta.",
    lat: 38.7201,
    lng: -9.4482,
  },
  {
    id: "qm-002",
    zone: "Quinta da Marinha",
    zone_tier: 1,
    typology: "T4",
    price_current: 1950000,
    price_initial: 1950000,
    area_sqm: 310,
    days_on_market: 18,
    seller_type: "agência",
    priority: "MEDIUM",
    score: 71,
    status: "Por contactar",
    listing_url: "https://example.com/listing/qm-002",
    commercial_note:
      "Anúncio recente, ainda sem redução de preço. Vendido através de agência — esperar resposta mais lenta.",
    lat: 38.7188,
    lng: -9.4461,
  },
  {
    id: "br-001",
    zone: "Birre",
    zone_tier: 1,
    typology: "Moradia",
    price_current: 1680000,
    price_initial: 1890000,
    area_sqm: 280,
    days_on_market: 96,
    seller_type: "particular",
    priority: "HIGH",
    score: 88,
    status: "Contactado",
    listing_url: "https://example.com/listing/br-001",
    commercial_note:
      "Já contactado a 12 dias — sem resposta ainda. Redução de 11% sugere disponibilidade para negociar.",
    lat: 38.7172,
    lng: -9.4248,
  },
  {
    id: "br-002",
    zone: "Birre",
    zone_tier: 1,
    typology: "T3",
    price_current: 980000,
    price_initial: 1050000,
    area_sqm: 195,
    days_on_market: 64,
    seller_type: "agência",
    priority: "MEDIUM",
    score: 68,
    status: "Por contactar",
    listing_url: "https://example.com/listing/br-002",
    commercial_note:
      "Preço já ajustado uma vez. Boa relação preço/área para a zona, procura deve ser elevada.",
    lat: 38.7159,
    lng: -9.4221,
  },
  {
    id: "gc-001",
    zone: "Guincho",
    zone_tier: 1,
    typology: "Moradia",
    price_current: 3400000,
    price_initial: 3400000,
    area_sqm: 510,
    days_on_market: 7,
    seller_type: "particular",
    priority: "HIGH",
    score: 91,
    status: "Por contactar",
    listing_url: "https://example.com/listing/gc-001",
    commercial_note:
      "Anúncio muito recente, vista mar direta. Proprietário particular — janela de oportunidade antes de mediação entrar.",
    lat: 38.7331,
    lng: -9.4727,
  },
  {
    id: "gc-002",
    zone: "Guincho",
    zone_tier: 1,
    typology: "T4",
    price_current: 2100000,
    price_initial: 2350000,
    area_sqm: 340,
    days_on_market: 210,
    seller_type: "agência",
    priority: "LOW",
    score: 42,
    status: "Em negociação",
    listing_url: "https://example.com/listing/gc-002",
    commercial_note:
      "Já em negociação avançada com outro comprador, segundo a agência. Acompanhar mas baixa prioridade imediata.",
    lat: 38.7308,
    lng: -9.4695,
  },
  {
    id: "me-001",
    zone: "Monte Estoril",
    zone_tier: 1,
    typology: "T3",
    price_current: 1150000,
    price_initial: 1290000,
    area_sqm: 175,
    days_on_market: 118,
    seller_type: "particular",
    priority: "HIGH",
    score: 86,
    status: "Por contactar",
    listing_url: "https://example.com/listing/me-001",
    commercial_note:
      "Redução de 11% e mais de 100 dias no mercado. Forte candidato a outreach prioritário.",
    lat: 38.7041,
    lng: -9.4091,
  },
  {
    id: "me-002",
    zone: "Monte Estoril",
    zone_tier: 1,
    typology: "T2",
    price_current: 720000,
    price_initial: 720000,
    area_sqm: 110,
    days_on_market: 22,
    seller_type: "agência",
    priority: "LOW",
    score: 38,
    status: "Por contactar",
    listing_url: "https://example.com/listing/me-002",
    commercial_note:
      "Preço de entrada para a zona, sem sinais de urgência de venda.",
    lat: 38.7029,
    lng: -9.4072,
  },
  {
    id: "cc-001",
    zone: "Cascais Centro",
    zone_tier: 2,
    typology: "T3",
    price_current: 890000,
    price_initial: 980000,
    area_sqm: 150,
    days_on_market: 75,
    seller_type: "particular",
    priority: "MEDIUM",
    score: 65,
    status: "Contactado",
    listing_url: "https://example.com/listing/cc-001",
    commercial_note:
      "Primeira mensagem enviada, aguarda resposta. Localização central, boa procura para arrendamento turístico.",
    lat: 38.6975,
    lng: -9.4208,
  },
  {
    id: "cc-002",
    zone: "Cascais Centro",
    zone_tier: 2,
    typology: "T2",
    price_current: 650000,
    price_initial: 690000,
    area_sqm: 95,
    days_on_market: 45,
    seller_type: "agência",
    priority: "MEDIUM",
    score: 58,
    status: "Por contactar",
    listing_url: "https://example.com/listing/cc-002",
    commercial_note:
      "Apartamento reformado, pequena redução de preço. Zona com alta liquidez.",
    lat: 38.6989,
    lng: -9.4231,
  },
  {
    id: "es-001",
    zone: "Estoril",
    zone_tier: 2,
    typology: "T4",
    price_current: 1480000,
    price_initial: 1480000,
    area_sqm: 260,
    days_on_market: 12,
    seller_type: "particular",
    priority: "MEDIUM",
    score: 73,
    status: "Por contactar",
    listing_url: "https://example.com/listing/es-001",
    commercial_note:
      "Anúncio recente, perto do casino. Proprietário particular, vale a pena contacto inicial.",
    lat: 38.7048,
    lng: -9.3958,
  },
  {
    id: "es-002",
    zone: "Estoril",
    zone_tier: 2,
    typology: "Moradia",
    price_current: 2250000,
    price_initial: 2600000,
    area_sqm: 390,
    days_on_market: 264,
    seller_type: "particular",
    priority: "HIGH",
    score: 90,
    status: "Por contactar",
    listing_url: "https://example.com/listing/es-002",
    commercial_note:
      "Mais de 8 meses no mercado e redução de 13%. Sinal forte de motivação para vender.",
    lat: 38.7061,
    lng: -9.3979,
  },
  {
    id: "es-003",
    zone: "Estoril",
    zone_tier: 2,
    typology: "T3",
    price_current: 940000,
    price_initial: 940000,
    area_sqm: 160,
    days_on_market: 5,
    seller_type: "agência",
    priority: "LOW",
    score: 35,
    status: "Por contactar",
    listing_url: "https://example.com/listing/es-003",
    commercial_note: "Anúncio muito recente, ainda sem sinais de negociação.",
    lat: 38.7033,
    lng: -9.3941,
  },
  {
    id: "qm-003",
    zone: "Quinta da Marinha",
    zone_tier: 1,
    typology: "Moradia",
    price_current: 4200000,
    price_initial: 4200000,
    area_sqm: 580,
    days_on_market: 30,
    seller_type: "agência",
    priority: "MEDIUM",
    score: 70,
    status: "Fechado",
    listing_url: "https://example.com/listing/qm-003",
    commercial_note: "Negócio fechado em maio. Manter como referência de zona.",
    lat: 38.7212,
    lng: -9.4501,
  },
  {
    id: "br-003",
    zone: "Birre",
    zone_tier: 1,
    typology: "T4",
    price_current: 1320000,
    price_initial: 1480000,
    area_sqm: 250,
    days_on_market: 88,
    seller_type: "particular",
    priority: "HIGH",
    score: 82,
    status: "Em negociação",
    listing_url: "https://example.com/listing/br-003",
    commercial_note:
      "Em negociação ativa — proprietário recetivo a contrapropostas.",
    lat: 38.7148,
    lng: -9.4259,
  },
  {
    id: "gc-003",
    zone: "Guincho",
    zone_tier: 1,
    typology: "T3",
    price_current: 1550000,
    price_initial: 1550000,
    area_sqm: 190,
    days_on_market: 50,
    seller_type: "particular",
    priority: "MEDIUM",
    score: 62,
    status: "Por contactar",
    listing_url: "https://example.com/listing/gc-003",
    commercial_note: "Vista parcial de mar, sem redução de preço até agora.",
    lat: 38.7294,
    lng: -9.4683,
  },
  {
    id: "me-003",
    zone: "Monte Estoril",
    zone_tier: 1,
    typology: "T5",
    price_current: 2680000,
    price_initial: 2980000,
    area_sqm: 400,
    days_on_market: 175,
    seller_type: "agência",
    priority: "HIGH",
    score: 84,
    status: "Por contactar",
    listing_url: "https://example.com/listing/me-003",
    commercial_note:
      "Redução de 10% e quase 6 meses no mercado. Agência pode estar mais flexível em comissão.",
    lat: 38.7053,
    lng: -9.4106,
  },
  {
    id: "cc-003",
    zone: "Cascais Centro",
    zone_tier: 2,
    typology: "T2",
    price_current: 580000,
    price_initial: 580000,
    area_sqm: 80,
    days_on_market: 9,
    seller_type: "particular",
    priority: "LOW",
    score: 30,
    status: "Por contactar",
    listing_url: "https://example.com/listing/cc-003",
    commercial_note: "Anúncio recente, tipologia de entrada, baixa urgência.",
    lat: 38.6962,
    lng: -9.4189,
  },
];
